server:
  port: 8001
spring:
  application:
    name: cloud-payment-service
  datasource:
    url: jdbc:mysql://imikasa.com:3309/lnfvc
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root

mybatis:
  mapper-locations: classpath:mapper/*.xml